'use strict';

// Wan: for localhost
module.exports = {
  up: (queryInterface, Sequelize) => {

    return queryInterface.bulkInsert('Products', [
      {
        type:"Furniture",
        sellerId:"5",
        title:"Boss Cat Bed",
        description:"Easy to play with your cat: 360 ° rotatable, 30 ° inclination for easy jumping in \nEasy to clean material: detachable soft fiber pad. Environmentally friendly and comfortable fiber lining inside \nStable stand and comfortable material: Anti-skid and spill. Extra support at the bottom prevents cat from hurting",
        detail:"\nFurrytail Boss cat bed x1\nFiber lining x1\nScrew Toolkit x1\nDonuts plastic clipx1\nManual",
        imgUrl:"http://localhost:3000/imgs/products/01-roundbed.webp",
        price: 87.9,
        inventory: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Furniture",
        sellerId:"5",
        title:"Cat Window Perch",
        description:"A VIP viewing platform for a curious cat\nA good resting seat for sunbathing\nHeavy-duty and reliable suction\nStrong and simple structure for easy installation and removal\nHigh quality material, with cat hair resistant PVC material or Fabric material for scratching\nSuction cup is reusable after washed in warm water",
        detail:"",
        imgUrl:"http://localhost:3000/imgs/products/02-cat-window-perch.webp",
        price: 119.99,
        inventory: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Furniture",
        sellerId:"5",
        title:"Circuit Ball Toy with Scratch Pad",
        description:"Circuit Ball Toy with Scratch Pad and Crazy bouncy bee.",
        detail:"Shake or vacuum out excess hair and debris. For best results, hand wash using mild detergent. No bleach. Rinse. Do not wring. Blot out excess water with towel before placing in dryer on Low. May be washed separately in front loading washing machine on delicate cycle only. Do not wash in washer with agitator.",
        imgUrl:"http://localhost:3000/imgs/products/03-Circuit-Ball-Toy-with-Scratch-Pad-copy.jpeg",
        price: 18.99,
        inventory: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"LED Flower Fountain",
        description:"Cat Drinking Fountain with LED Nightlight and Petal Top",
        detail:"Note: Cats usually begin to appreciate catnip between 6 and 8 months of age. To keep catnip fresh, store in a safe, cool , dark place. Catnip is an herb that grows naturally in the environment. Catnip is considered safe for animals and humans. We recommend catnip be used exclusively by cats. It is not intended for human consumption. Monitor play.",
        imgUrl:"http://localhost:3000/imgs/products/04-LED-flower-fountain_hero-shot-1.jpeg",
        price: 29.99,
        inventory: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"Catit Creamy Feeding Mat",
        description:"Fish-shaped silicone mat. Food-grade, dishwasher-safe silicone.",
        detail:"Hand washable with mild soap and water.",
        imgUrl:"http://localhost:3000/imgs/products/05-Catit_Creamy-Mat_Panel-1_NA-EN.jpeg",
        price: 6.99,
        inventory: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Toys & Catnip",
        sellerId:"8",
        title:"Catit Pure Catnip",
        description:"Pure, dried catnip leaves and flowers of Canadian quality",
        detail:"Available in 14g (0.5 oz), 28g (1 oz), 56g (2 oz)",
        imgUrl:"http://localhost:3000/imgs/products/06-Catit_Catnip_Panel-1_NA-EN-1.jpeg",
        price: 8.49,
        inventory: 400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Toys & Catnip",
        sellerId:"8",
        title:"Catit Catnip Spray",
        description:"Concentrated extract of pure catnip. Apply where you want your cat to play or scratch. Great on cat toys, scratching posts and fabrics",
        detail:"90 ml (3 fl oz)",
        imgUrl:"http://localhost:3000/imgs/products/07-Catit_Catnip-Spray_Panel-1_NA-EN.jpeg",
        price: 8.49,
        inventory: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        type:"Traveling",
        sellerId:"6",
        title:"Foldable Cat Backpack",
        description:"Easy to play with your cat: 360 ° rotatable, 30 ° inclination for easy jumping in \nEasy to clean material: detachable soft fiber pad. Environmentally friendly and comfortable fiber lining inside \nStable stand and comfortable material: Anti-skid and spill. Extra support at the bottom prevents cat from hurting",
        detail:"Backpack cover*1\nBackpack middle part*1\nBackpack bottom*1\nAssembly instruction*1",
        imgUrl:"http://localhost:3000/imgs/products/08-foldable-backpack.webp",
        price: 119.99,
        inventory: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Traveling",
        sellerId:"6",
        title:"Wild One Travel Carrier",
        description:"Travel together with this super comfortable, modular Travel Carrier. With breathable mesh walls, a dual use leash / shoulder strap, and an interior cushion that folds out to become a comfortable dog bed, our airline compliant carrier is the home away from home your dog deserves. ",
        detail:"Size: L - 17.5” (45 cm) / W - 11” (28 cm) / H - 10” (25 cm)]\nRecommended for use with dogs up to 16 lbs (7 kg)",
        imgUrl:"http://localhost:3000/imgs/products/09-TravelCarrier_Spruce_Dog_05_Web_800x1000_crop_center.webp",
        price: 125.5,
        inventory: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Furniture",
        sellerId:"5",
        title:"Catit Stacking Tower – Square",
        description:"Ruling their domain. The padded top perch is an excellent spot for your cat to people watch or catch some sunshine. ",
        detail:"Ideal starter furniture for kittens",
        imgUrl:"http://localhost:3000/imgs/products/10-Catit_Stacking_SQUARE_Tower_Panel-1_NA-EN.jpeg",
        price: 249.99,
        inventory: 1000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"Pet NMN",
        description:"The FIRST anti-aging product tailored for pets, approved by the United States Food and Drug Administration (U.S. FDA).",
        detail:"Sugar and Weight control. Feeding Instruction: 30 fish shape capusles every time.",
        imgUrl:"http://localhost:3000/imgs/products/11-Pet-NMN.webp",
        price: 49.9,
        inventory: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"Salmon Jerky",
        description:"Made with 100% salmon jerky with no additives, fillers, color, or preservatives. Tasted chewy brings pure nutrients and energy to your furry friends. Proudly developed and produced in Canada with our exclusive patent formula",
        detail:"Feed as a healthy treat for your cat, break into pieces for small cats and always monitor your pet while treating. Fresh drinking water should always be available.",
        imgUrl:"http://localhost:3000/imgs/products/12-salmon-jerky.webp",
        price: 9.9,
        inventory: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"Wild Salmon Pâte-Grain free wet cat food",
        description:"Made with Canadian wild salmon, proudly developed and produced in Canada. Flavors your cat will love. Grain free and no artificial colors, flavors or preservatives. For cats of all ages.  Meet the high protein need. Good for digestion and hair quality",
        detail:"Feed as a healthy treat for your cat, break into pieces for small cats and always monitor your pet while treating. Fresh drinking water should always be available.",
        imgUrl:"http://localhost:3000/imgs/products/13-salmonpatesmall_1080x.webp",
        price: 6.9,
        inventory: 80,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"Tiki Cat® After Dark™ Chicken Recipe in Broth",
        description:"Give cats the real meat they crave with succulent shredded chicken and organ meat in a savory broth.",
        detail:"Recommendations vary greatly, based on your cat’s age, activity level and life stage. For adult cats, feed approximately 2-3 cans/pouches per day per 7 lbs. of body weight. For kittens, offer food several times a day, feed up to twice this amount.",
        imgUrl:"http://localhost:3000/imgs/products/14-TC_AfterDark_Chicken.png",
        price: 5.9,
        inventory: 80,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"Tiki Cat® Aloha Friends™ Tuna, Calamari & Pumpkin",
        description:"Flaked tuna with pumpkin and indulgent calamari in a savory tuna broth. Grain & Potato Free",
        detail:"Recommendations vary greatly, based on your cat’s age, activity level and life stage. For adult cats, feed approximately 2-3 cans/pouches per day per 7 lbs. of body weight. For kittens, offer food several times a day, feed up to twice this amount.",
        imgUrl:"http://localhost:3000/imgs/products/15-Tiki-Cat-Aloha-Friends-3-oz.-can-12-TR-Tuna-Calamari-Pumpkin-1.png",
        price: 8.9,
        inventory: 80,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"Weruva® Chicken Formula Au Jus",
        description:"Get ready for your kitten to dash over to their bowl to lap up this tasty meal! The shredded chicken in an au jus will make them jump for joy until you open up the next can.",
        detail:"Chicken, Chicken Broth, Natural Flavor, Dried Egg, Tricalcium Phosphate, Sunflower Oil, Guar Gum, Xanthan Gum, Locust Bean Gum, Fish Oil, Choline Chloride, Taurine, Zinc Sulfate, Ferrous Sulfate, Vitamin E Supplement, Thiamine Mononitrate (Vitamin B1), Niacin Supplement (Vitamin B3), Calcium Pantothenate, Vitamin A Supplement, Manganese Sulfate, Copper Sulfate, Riboflavin Supplement (Vitamin B2), Pyridoxine Hydrochloride (Vitamin B6), Vitamin D3 Supplement, Folic Acid, Vitamin B12 Supplement, Potassium Iodide",
        imgUrl:"http://localhost:3000/imgs/products/16-WRV_KITTEN-CHICKEN_3.0OZ-CAN-01-WEB-1024x1024.jpg",
        price: 8.9,
        inventory: 80,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Food & Feeder",
        sellerId:"4",
        title:"Wild One Bowl Kit",
        description:"Double up & save on our timelessly simple, non-slip Bowls. Made with food-grade stainless steel to hold 4 cups of food for the hungriest of dogs. A perfectly scooped bowl ensures no food is left behind in crevices or corners. Plus, they're top-rack dishwasher safe!",
        detail:"Dimensions: 7.72” x 7.72” x 3.15” \nVolume: 32 fl oz (4 cups)",
        imgUrl:"http://localhost:3000/imgs/products/17-WO_VM_Studio_PDP_Bowl_Lilac_03_Web_2_7471908d-8095-411b-90b4-eeb6e8b73f62_800x1000_crop_center.webp",
        price: 48,
        inventory: 1000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Cleaning & Litter",
        sellerId:"7",
        title:"Dust-free Clumping Cat Litter-Flushable",
        description:"Dust-free, clumping\nMixed with natural Tofu\nWater dissolvable and flushable\nEnvironmentally friendly\nStrong odor control",
        detail:"5.5lb/bag",
        imgUrl:"http://localhost:3000/imgs/products/18-super-litter.jpeg",
        price: 48,
        inventory: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Cleaning & Litter",
        sellerId:"7",
        title:"Pet Cleaning Gloves",
        description:"Easy to use, just wear one glove and massage the essence throughout the body, and dry naturally. \nDeodorize with natural herbs, safe to use or even lick",
        detail:"Color: white\nMaterial: non-woven fabric\nProduct size: 10*16cm",
        imgUrl:"http://localhost:3000/imgs/products/19-cleaning-gloves.webp",
        price: 16.5,
        inventory: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Cleaning & Litter",
        sellerId:"7",
        title:"Glow House Cat Litter Box",
        description:"From now on, your beloved cats have their first villa! Furrytail builds pet litter box like an architect builds a house, which invests litter box with the beauty of stylish architecture. Featuring a grate on the right side (corridor), ensures cat to crosses grate upon exiting the Glow House, controlling scatter and recycling collected litter. Pet litter house should not be a total enclosed dark room. The Glow House’s door creates privacy, while the semi-open corridor enables ventilation.",
        detail:"Dimensions: 20.72” x 25.72” x 18.15”",
        imgUrl:"http://localhost:3000/imgs/products/20-house-litter-box.webp",
        price: 187.99,
        inventory: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Grooming",
        sellerId:"5",
        title:"Longhair Grooming Kit",
        description:"The Catit Longhair Grooming Kit contains every tool you need to take care of a medium- to longhaired cat’s coat. Stored upright to protect the brush tips.",
        detail:"Made of BPA-free materials",
        imgUrl:"http://localhost:3000/imgs/products/21-Longhair-Grooming-Kit-1.jpeg",
        price: 39.99,
        inventory: 300,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        type:"Grooming",
        sellerId:"5",
        title:"Senses 2.0 Self Groomer",
        description:"Provide your cat with a constant source of rubbing and grooming pleasure. Awarded a 2017 ‘Cat Friendly’ award by International Cat Care!",
        detail:"Made of BPA-free materials",
        imgUrl:"http://localhost:3000/imgs/products/22-Senses-2.0-Self-Groomer.jpg",
        price: 4.99,
        inventory: 300,
        createdAt: new Date(),
        updatedAt: new Date(),
      },




    ], {});

  },

  down: (queryInterface, Sequelize) => {

    return queryInterface.bulkDelete('Products', null, {});

  }
};


